[package]
name = "example"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zxtouch = { path = "..", features = ["debug-print"] }
tokio = { version = "1.35.1", features = ["full"] }
